version: 2

sources:
  - name: circle
    schema: raw_data_circle
    tables:
      - name: funnel
        identifier: raw_cc_funnel
      - name: funnel_priority
        identifier: raw_cc_funnel_priority